ServerEvents.tags('item', event => {

// Crafting Tables
event.add('mctb:revertable_workbench','mctb:alpha_crafting_table')
event.add('mctb:revertable_workbench','mctb:baobab_crafting_table')
event.add('mctb:revertable_workbench','mctb:blackwood_crafting_table')
event.add('mctb:revertable_workbench','mctb:blue_bioshroom_crafting_table')
event.add('mctb:revertable_workbench','mctb:brimwood_crafting_table')
event.add('mctb:revertable_workbench','mctb:cobalt_crafting_table')
event.add('mctb:revertable_workbench','mctb:cypress_crafting_table')
event.add('mctb:revertable_workbench','mctb:ru_dead_crafting_table')
event.add('mctb:revertable_workbench','mctb:eucalyptus_crafting_table')
event.add('mctb:revertable_workbench','mctb:green_bioshroom_crafting_table')
event.add('mctb:revertable_workbench','mctb:joshua_crafting_table')
event.add('mctb:revertable_workbench','mctb:kapok_crafting_table')
event.add('mctb:revertable_workbench','mctb:larch_crafting_table')
event.add('mctb:revertable_workbench','mctb:magnolia_crafting_table')
event.add('mctb:revertable_workbench','mctb:maple_crafting_table')
event.add('mctb:revertable_workbench','mctb:mauve_crafting_table')
event.add('mctb:revertable_workbench','mctb:ru_palm_crafting_table')
event.add('mctb:revertable_workbench','mctb:pine_crafting_table')
event.add('mctb:revertable_workbench','mctb:pink_bioshroom_crafting_table')
event.add('mctb:revertable_workbench','mctb:ru_redwood_crafting_table')
event.add('mctb:revertable_workbench','mctb:ru_willow_crafting_table')
event.add('mctb:revertable_workbench','mctb:yellow_bioshroom_crafting_table')
event.add('mctb:revertable_workbench','mctb:socotra_crafting_table')

// Drill Heads
event.add('createoreexcavation:drills','createoreexcavation:brass_drill')
event.add('createoreexcavation:drills','createoreexcavation:desh_drill')
event.add('createoreexcavation:drills','createoreexcavation:ostrum_drill')
event.add('createoreexcavation:drills','createoreexcavation:calorite_drill')
event.add('createoreexcavation:drills','createoreexcavation:dragon_drill')
event.add('createoreexcavation:drills','createoreexcavation:amber_drill')
event.add('createoreexcavation:drills','createoreexcavation:azure_drill')
event.add('createoreexcavation:drills','createoreexcavation:guano_drill')
event.add('createoreexcavation:drills','createoreexcavation:pearl_drill')
event.add('createoreexcavation:drills','createoreexcavation:scarlet_drill')
event.add('createoreexcavation:drills','createoreexcavation:sulfur_drill')
event.add('createoreexcavation:drills','createoreexcavation:uranium_drill')
event.add('createoreexcavation:drills','createoreexcavation:echo_drill')

// Ad Astra Ores
event.add('forge:ores/ice_shard', 'ad_astra:moon_ice_shard_ore' )
event.add('forge:ores/ice_shard', 'ad_astra:deepslate_ice_shard_ore' )
event.add('forge:ores/ice_shard', 'ad_astra:mars_ice_shard_ore' )
event.add('forge:ores/ice_shard', 'ad_astra:glacio_ice_shard_ore' )
event.add('forge:ores/cheese','ad_astra:moon_cheese_ore')
event.add('forge:ores/desh','ad_astra:moon_desh_ore')
event.add('forge:ores/desh','ad_astra:deepslate_desh_ore')
event.add('forge:ores/ostrum','ad_astra:mars_ostrum_ore')
event.add('forge:ores/ostrum','ad_astra:deepslate_ostrum_ore')
event.add('forge:ores/calorite','ad_astra:venus_calorite_ore')
event.add('forge:ores/calorite','ad_astra:deepslate_calorite_ore')

// Alex Caves Ores
event.add('forge:ores/redstone', 'alexscaves:guanostone_redstone_ore')
event.add('forge:ores/coal', 'alexscaves:coprolith_coal_ore')
event.add('forge:ores/uranium', 'alexscaves:radrock_uranium_ore')

// Enlightened End Ores
event.add('forge:ores/bismuth','enlightened_end:bismuth_ore')
event.add('forge:ores/irradium','enlightened_end:irradium_ore')
event.add('forge:ores/malachite','enlightened_end:malachite_ore')

// forge:templates/smithing
event.add('forge:templates/smithing','minecraft:netherite_upgrade_smithing_template')
event.add('forge:templates/smithing','forge_frontier:netherite_iron_upgrade')
event.add('forge:templates/smithing','forge_frontier:netherite_gold_upgrade')
event.add('forge:templates/smithing','forge_frontier:netherite_emerald_upgrade')
event.add('forge:templates/smithing','forge_frontier:netherite_diamond_upgrade')
event.add('forge:templates/smithing','cataclysm:ignitium_upgrade_smithing_template')
event.add('forge:templates/smithing','enlightened_end:adamantite_smithing_template')
event.add('forge:templates/smithing','ethuim:ethium_upgrade_smithing_template')
event.add('forge:templates/smithing','endreborn:mysterious_upgrade_template')
event.add('forge:templates/smithing','endreborn:curious_upgrade_template')
event.add('forge:templates/smithing','deeperdarker:warden_upgrade_smithing_template')
event.add('forge:templates/smithing','create_additions_synthetics:gilded_upgrade')

// forge:enegergized/items
event.add('forge:energized/items','create_new_age:overcharged_iron')
event.add('forge:energized/items','create_new_age:overcharged_golden_sheet')
event.add('forge:energized/items','create_new_age:overcharged_diamond')
event.add('forge:energized/items','create_new_age:overcharged_gold')
event.add('forge:energized/items','create_new_age:overcharged_iron_sheet')
event.add('forge:energized/items','forge_frontier:overcharged_netherite_ingot')

// create:crushed_raw_materials
event.add('create:crushed_raw_materials','forge_frontier:crushed_desh')
event.add('create:crushed_raw_materials','forge_frontier:crushed_ostrum')
event.add('create:crushed_raw_materials','forge_frontier:crushed_calorite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_bismuth')
event.add('create:crushed_raw_materials','forge_frontier:crushed_irradium')
event.add('create:crushed_raw_materials','forge_frontier:crushed_malachite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_redstone')
event.add('create:crushed_raw_materials','forge_frontier:crushed_verdantine')
event.add('create:crushed_raw_materials','forge_frontier:crushed_glacium')
event.add('create:crushed_raw_materials','forge_frontier:crushed_debris')
event.add('create:crushed_raw_materials','forge_frontier:crushed_grime')
event.add('create:crushed_raw_materials','forge_frontier:crushed_aubrum')
event.add('create:crushed_raw_materials','forge_frontier:crushed_pyroclast')
event.add('create:crushed_raw_materials','forge_frontier:crushed_frostite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_stellaris')
event.add('create:crushed_raw_materials','forge_frontier:crushed_radiantite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_shale')
event.add('create:crushed_raw_materials','forge_frontier:crushed_palerock')
event.add('create:crushed_raw_materials','forge_frontier:crushed_guanite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_pearlyte')
event.add('create:crushed_raw_materials','forge_frontier:crushed_amberlite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_azurnium')
event.add('create:crushed_raw_materials','forge_frontier:crushed_neodymrium')
event.add('create:crushed_raw_materials','forge_frontier:crushed_uraniumnite')
event.add('create:crushed_raw_materials','forge_frontier:crushed_sulphite')

// forge_frontier:end_remastered_eye_pieces
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:pirate_arrow')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:pirate_crossbow')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:cannon_ball')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:soul_flame_staff')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:infernal_ingot')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:ras_solar_sword')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:sun_disc')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:piglin_kings_crown')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:piglin_war_axe')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:piglin_totem')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:infernal_chisel')
event.add('forge_frontier:end_remastered_eye_pieces','forge_frontier:hellhounds_fang')

// forge_frontier:molds
event.add('forge_frontier:mold_templates','forge_frontier:upgrade_mold')
event.add('forge_frontier:mold_templates','forge_frontier:axe_mold')
event.add('forge_frontier:mold_templates','forge_frontier:boots_mold')
event.add('forge_frontier:mold_templates','forge_frontier:block_mold')
event.add('forge_frontier:mold_templates','forge_frontier:chestplate_mold')
event.add('forge_frontier:mold_templates','forge_frontier:coal_mold')
event.add('forge_frontier:mold_templates','forge_frontier:gem_mold')
event.add('forge_frontier:mold_templates','forge_frontier:head_mold')
event.add('forge_frontier:mold_templates','forge_frontier:helmet_mold')
event.add('forge_frontier:mold_templates','forge_frontier:hoe_mold')
event.add('forge_frontier:mold_templates','forge_frontier:ingot_mold')
event.add('forge_frontier:mold_templates','forge_frontier:legginings_mold')
event.add('forge_frontier:mold_templates','forge_frontier:pickaxe_mold')
event.add('forge_frontier:mold_templates','forge_frontier:shovel_mold')
event.add('forge_frontier:mold_templates','forge_frontier:skull_mold')
event.add('forge_frontier:mold_templates','forge_frontier:sword_mold')
event.add('forge_frontier:mold_templates','forge_frontier:mold_template')

// Vanilla Tag
event.add('forge_frontier:vanilla','minecraft:dandelion')
event.add('forge_frontier:vanilla','minecraft:blue_orchid')

})

ServerEvents.tags('fluid', event => {

    // Fluids
    event.add('forge:crude_oil','ad_astra:oil')
    event.remove('minecraft:water', 'createaddition:bioethanol')
    
})

