
ServerEvents.tags('block', event => {
    
    // Create Wrenchable
    event.add('create:wrench_pickup', [
        'create:schematicannon',
        'create:schematic_table',
        'iammusicplayer:music_manager',
        'iammusicplayer:cassette_deck',
        'iammusicplayer:boombox',
        'chargers:charger_t1',
        'chargers:charger_t2',
        'chargers:charger_t3',
        'chargers:charger_t4',
        'chargers:wireless_charger',
        'sophisticatedstorage:controller',
        'sophisticatedstorage:storage_link',
        'sophisticatedstorage:storage_io',
        'sophisticatedstorage:storage_input',
        'sophisticatedstorage:storage_output',
        'farmersdelight:cooking_pot',
        'farmersdelight:skillet',
        'farmersdelight:cutting_board',
        'aquaculture:tackle_box',
        'easy_villagers:incubator',
        'easy_villagers:converter',
        'easy_villagers:breeder',
        'easy_villagers:farmer',
        'easy_villagers:auto_trader',
        'easy_villagers:trader',
        'chipped:tinkering_table',
        'chipped:alchemy_bench',
        'chipped:mason_table',
        'chipped:loom_table',
        'chipped:carpenters_table',
        'chipped:glassblower',
        'chipped:botanist_workbench',
        'toms_storage:ts.level_emitter',
        'toms_storage:ts.inventory_hopper_basic',
        'toms_storage:ts.crafting_terminal',
        'toms_storage:ts.inventory_proxy',
        'toms_storage:ts.inventory_cable_connector_framed',
        'toms_storage:ts.inventory_cable_connector_filtered',
        'toms_storage:ts.inventory_cable_connector',
        'toms_storage:ts.inventory_cable_framed',
        'toms_storage:ts.inventory_cable',
        'toms_storage:ts.open_crate',
        'toms_storage:ts.trim',
        'toms_storage:ts.storage_terminal',
        'toms_storage:ts.inventory_connector',
        'bobberdetector:bobber_detector',
        'hyperbox:hyperbox',
        'pipez:item_pipe',
        'pipez:fluid_pipe',
        'pipez:energy_pipe',
        'pipez:universal_pipe',
        'ad_astra:desh_fluid_pipe',
        'ad_astra:ostrum_fluid_pipe',
        'ad_astra:cable_duct',
        'ad_astra:fluid_pipe_duct',
        'ad_astra:coal_generator',
        'ad_astra:compressor',
        'ad_astra:etrionic_blast_furnace',
        'ad_astra:fuel_refinery',
        'ad_astra:oxygen_loader',
        'ad_astra:solar_panel',
        'ad_astra:water_pump',
        'ad_astra:oxygen_distributor',
        'ad_astra:gravity_normalizer',
        'ad_astra:energizer',
        'ad_astra:cryo_freezer',
        'ad_astra:oxygen_sensor',
        'ad_astra:launch_pad',
        'ad_astra:vent',
        'ad_astra:radio',
        'ad_astra_giselle_addon:gravity_normalizer',
        'ad_astra_giselle_addon:rocket_sensor',
        'ad_astra_giselle_addon:fuel_loader',
        'miners_delight:copper_pot',
        'farmersrespite:kettle',
        '#botanypots:all_botany_pots',
        '#chipped:lantern',
        '#chipped:soul_lantern',
        '#ad_astra:globes',
        '#ad_astra:sliding_doors'
    ]);

// Remove Non_Movable Tag Items
event.remove('create:non_movable', [
    'molten_vents:active_molten_asurine',
    'molten_vents:active_molten_veridium',
    'molten_vents:active_molten_crimsite',
    'molten_vents:active_molten_ochrum',
    'molten_vents:active_molten_scorchia',
    'molten_vents:active_molten_scoria',
    'molten_vents:dormant_molten_asurine',
    'molten_vents:dormant_molten_veridium',
    'molten_vents:dormant_molten_crimsite',
    'molten_vents:dormant_molten_ochrum',
    'molten_vents:dormant_molten_scorchia',
    'molten_vents:dormant_molten_scoria'
]);


});