ServerEvents.recipes(event => {

        // Removes Missing MCTB Recipes
        event.remove({ id: 'mctb:blossom_crafting_table'})
        event.remove({ id: 'mctb:archwood_planks_crafting_table'})
        event.remove({ id: 'mctb:hellbark_crafting_table'})
        event.remove({ id: 'mctb:grongle_crafting_table'})
        event.remove({ id: 'mctb:dark_crafting_table'})
        event.remove({ id: 'mctb:dead_crafting_table'})
        event.remove({ id: 'mctb:menril_planks_crafting_table'})
        event.remove({ id: 'mctb:sorting_crafting_table'})
        event.remove({ id: 'mctb:twilight_mangrove_crafting_table'})
        event.remove({ id: 'mctb:transformation_crafting_table'})
        event.remove({ id: 'mctb:umbran_crafting_table'})
        event.remove({ id: 'mctb:fir_crafting_table'})
        event.remove({ id: 'mctb:walnut_planks_crafting_table'})
        event.remove({ id: 'mctb:magic_crafting_table'})
        event.remove({ id: 'mctb:twilight_oak_crafting_table'})
        event.remove({ id: 'mctb:time_crafting_table'})
        event.remove({ id: 'mctb:demonic_planks_crafting_table'})
        event.remove({ id: 'mctb:willow_crafting_table'})
        event.remove({ id: 'mctb:ad_ancient_crafting_table'})
        event.remove({ id: 'mctb:palm_crafting_table'})
        event.remove({ id: 'mctb:soul_planks_crafting_table'})
        event.remove({ id: 'mctb:mining_crafting_table'})
        event.remove({ id: 'mctb:redwood_crafting_table'})
        event.remove({ id: 'mctb:jacaranda_crafting_table'})
        event.remove({ id: 'mctb:rubber_planks_crafting_table'})
        event.remove({ id: 'mctb:mahogany_crafting_table'})
        event.remove({ id: 'mctb:canopy_crafting_table'})
        event.remove({ id: 'mctb:wigglewood_crafting_table'})
        event.remove({ id: 'mctb:bop_cherry_crafting_table'})
        event.remove({ id: 'mctb:ancient_planks_crafting_table'})
        event.remove({ id: 'mctb:smogstem_crafting_table'})
        
})