#Hard disable entire modules. Use at your own risk and don't ask for support if you use this
#Thu Jan 02 21:30:35 PST 2025
chipped=true
farmersdelight=true
friendsandfoes=true
handcrafted=true
quark=true
twigs=true
