#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 02 21:30:33 PST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.3 + EuphoriaPatches_1.4.3
